version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on: 
      - db
  
  db:
    image: "postgres:11"
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    environment:
      - POSTGRES_USER=quanghuy
      - POSTGRES_PASSWORD=12345678  
      - POSTGRES_DB=main
